Repository softwareconstruction240/chess, pull requests merged in 2025-03, with the labels that each got.

#19 Add ChessGameTests
  starter-code/1-chess-game/passoff/chess/game/ChessGameTests.java
Labels: enhancement, requirements:low change

#22 Standardize phase3 tests
  starter-code/3-web-api/passoff/server/StandardAPITests.java
Labels: enhancement, requirements:no change

#23 Edit DatabaseManager.java to improve try blocks and documentation
  starter-code/3-web-api/dataaccess/DataAccessException.java
  starter-code/4-database/dataaccess/DatabaseManager.java
Labels: requirements:no change
